proc: fix missing reference of mm
The defconfig build of blackfin was failing with the error:
fs/proc/task_nommu.c: In function 'is_stack':
fs/proc/task_nommu.c:132:28: error: 'mm' undeclared (first use in this function)

While reverting /proc/<pid>/maps [stack:TID] annotation a reference to
mm was missed.

Fixes: e87d4fd02f40 ("proc: revert /proc/<pid>/maps [stack:TID] annotation")
CC: Johannes Weiner <hannes@cmpxchg.org>
Signed-off-by: Sudip Mukherjee <sudip@vectorindia.org>